server:
  port: 5010
#  servlet:
#    context-path: /consumer1

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true

# 配置集群eureka注册中心
eureka:
  client:
    #不对外提供服务，仅消费（访问）别的服务，所以不需要将自己注册到注册中心
    #register-with-eureka: false
    service-url:
      defaultZone: http://peer1:3001/eureka/,http://peer2:3002/eureka/
spring:
  application:
    name: consumer1
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true&verifyServerCertificate=false&characterEncoding=UTF-8
    username: root
    password: wscqtlulu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.springcloud.consumer1.pojo
  mapperLocations: classpath:mapper/*.xml

constant: constant0
